### ISSUE TITLE
PHP Unit not working ,its throwing error

### ISSUE THREAD

**Issue by rockers007** [Porto-SAP/Hello-API#100]
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configur
ation::getTestdoxGroupConfiguration() in D:\xampp\htdocs\angular\Hello-API\vendo
r\phpunit\phpunit\src\TextUI\TestRunner.php:1076
Stack trace:
#0 D:\xampp\htdocs\angular\Hello-API\vendor\phpunit\

**Comment by rockers007** [comment]
Solved ,its was version issue...need to upgrade phpunit version. but
phpunit does not test any case...
when I run "phpunit" command then output say No tests executed !

**Comment by Mahmoudz** [comment]
I don't know how you are trying to run your tests, probably you are calling the tests on the root directory, I got that folder "tests" back while migrating to Laravel 5.4. in case someone wants anything from it! Anyway check your `phpunit.xml` file.
