### ISSUE TITLE
Containers Generator

### ISSUE THREAD

**Issue by Mahmoudz** [Porto-SAP/Hello-API#56]
Example usage `php artisan container:create --name Post --fields title,body,status --routes post/create,post/delete ...` This should generate all the basic files with sample names:
- All the basic directories 
- Post Model
- UI for WEB and API including routes, controllers, requests,...
- Tests
- Data: PostRepository, Migrations, Factories
- Main ServiceProvider
- ............... everything else

**Comment by Mahmoudz** [comment]
On the way [https://github.com/Porto-SAP/Generator](https://github.com/Porto-SAP/Generator)...

**Comment by Funso-Popoola** [comment]
Please, what's the update with this feature? I just started using this adorable starter code and it soon became obvious how important this feature is and how much I need it.

**Comment by Mahmoudz** [comment]
@Funso-Popoola Hi, that's absolutely true, it's under development now ~60% done, I'm building it myself this time. 

I'm gonna release it by the end of this week or maybe before, even if it's not fully completed. And will continue adding features to it while it's available.. 

Stay tuned.

**Comment by johannesschobel** [comment]
Just wanted to push this question up.. Is this feature implemented and ready to use?

**Comment by Mahmoudz** [comment]
@johannesschobel thanks for your question, this feature is half implemented, hopefully should be ready by the end of this week (Sunday). You can see I've published the core code [here](https://github.com/apiato/apiato/tree/master/app/Ship/Features/Generator) to continue working on it this week. But first I must finish couple other stuff (like upgrading the tests to 5.4 since tests were rewritten from scratch and replacing Dingo and JWT with Passport and Laravel's built in support for API's...)

**Comment by johannesschobel** [comment]
Hey @Mahmoudz ,

thank you very much for your very fast response. It is very good to see, that this project (or in other words - you) is so active ;)
So basically you are dropping Dingo/Api support? Why not make it customizable? Same for JWT vs. Passport? Are there specific issues related to those 3rd-party-libs (except of adding another dependency)?

Maybe we can discuss on your Slack channel? I have other questions related to your awesome work as well :)
