### ISSUE TITLE
 Using Passport Laravel and Dingo in the proyect?

### ISSUE THREAD

**Issue by vdjkelly** [Porto-SAP/Hello-API#62]
It can be used in laravel passport hello dingo api for using the token??

**Comment by Mahmoudz** [comment]
@vdjkelly I couldn't understand what's your question!! are you suggesting to replace Dingo API / JWT packages with Laravel Passport?!

**Comment by vdjkelly** [comment]
@Mahmoudz Yes, if there are possibilities to change JWT by laravel passport as it offers more advantages not only work well if dingo and throttle rate limit

**Comment by Mahmoudz** [comment]
@vdjkelly yep I agree, I was considering that but never had the chance to try passport, I'll try to do that today.

**Comment by vdjkelly** [comment]
@Mahmoudz Please when I have news to tell hereby do, or update on a branch of the project with the integration of passport laravel

**Comment by Mahmoudz** [comment]
@vdjkelly sorry I didn't understand what you mean!!

**Comment by Mahmoudz** [comment]
@vdjkelly I'll close this for now, and I'll message you if I do any changes to that part.
