### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by cmburcus** [Porto-SAP/Hello-API#69]
Would you be able to add a demo site? I tried installing it but gave up after a couple of hickups. I simply wanted to see what it looks like / what it does once installed (especially the admin panel).

-------------------

For the issues (just as a heads up)

I followed method B of installing. After I cloned the project and linked it to my homestead machine, i tried running `php artisan containers:add User Welcome Authentication`

<img width="873" alt="screen shot 2016-11-30 at 10 48 23 am" src="https://cloud.githubusercontent.com/assets/11837178/20759335/af6a9396-b6ea-11e6-87fc-9db97d068ab3.png">

I left that one be and did a composer install instead. Everything installed but there are dependencies that I do not have on my machine. I let that be since i can install them manually, although I know clients who will refuse to have these sort of dependencies on their servers.

One thing went wrong at the end of the script however:

<img width="634" alt="screen shot 2016-11-30 at 10 53 14 am" src="https://cloud.githubusercontent.com/assets/11837178/20759586/48294fd2-b6eb-11e6-91b2-9bb395002b03.png">

I then simply tried to run `php artisan` and i received this:

<img width="356" alt="screen shot 2016-11-30 at 10 53 58 am" src="https://cloud.githubusercontent.com/assets/11837178/20759594/537d3db2-b6eb-11e6-800c-64c2ab1a9404.png">

Good initiative on this project. Looks like a lot of work and I would love to see a demo of it :)

**Comment by Mahmoudz** [comment]
@cmburcus could you try the Method A: `composer create-project --keep-vcs porto-sap/hello-api:dev-master hello-api` this will do everything for you automatically.

I will update the manual installation steps in the documentation soon.
