### ISSUE TITLE
Error optimize post-install-cmd

### ISSUE THREAD

**Issue by zeroc0d3** [Porto-SAP/Hello-API#70]
Hi @Mahmoudz, 

I got this error:
`App\Port\Provider\Abstracts\ServiceProviderAbstract and App\Port\Provider\Loaders\ProvidersLoaderTrait define the same property ($portProvidersDirectories) in the composition of App\Port\Provider\Providers\MainServiceProvider. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed`

when running `composer install`

my environment:
1) php-fpm 5.6 
2) nginx
3) mysql 5.5

**Comment by lucassmacedo** [comment]
i have same problem.

**Comment by Mahmoudz** [comment]
@zeroc0d3 @lucassmacedo can you please try it now to see if the problem is fixed? 
Thanks

**Comment by zeroc0d3** [comment]
Hi @Mahmoudz, 

I've found some error syntax but had been resolved in this [issue](https://github.com/Porto-SAP/Hello-API/issues/73), thanks
