### ISSUE TITLE
Question - web login

### ISSUE THREAD

**Issue by mitjarobic** [Porto-SAP/Hello-API#71]
Hi, 

if i submit the login web form and the App\Containers\Authentication\UI\WEB\Requests\LoginRequest fails I get the following response:

{"message":"Invalid Input.","errors":{"email":["The email field is required."],"password":["The password field is required."]},"status_code":422}

Shouldn't I get a  redirect response to send the user back to their previous location and errors flashed to session?

Can you please explain this feature?

Thanks

**Comment by nmrgt** [comment]
I think the error you are talking about is mentioned on #54

**Comment by Mahmoudz** [comment]
@mitjarobic if you could solve this and contribute back would be perfect, I believe Laravel 5.3 have something to deal with that by intercepting the request type...
(I personally never serve HTML from Hello API).

@nmrgt thanks for the reference.
