### ISSUE TITLE
Question: what if we want to write parallel some app that consume the API that we are writing?

### ISSUE THREAD

**Issue by llstarscreamll** [Porto-SAP/Hello-API#76]
Hi!!

If I want to create in parallel an application that consume the API for the container(s) created, where to put this code? Maybe:

- app
  - Containers
    - Users
      - Actions
      - Tasks
      - ...
      - **Consumers (or CLI's or whatever)** // here is the container for the platform app API consumer
        - Android
        - AngularJS
        - Angular 2
          - src // module bundle source
        - JavaDesktop
        - VB.Net

Off course, with Angular 2 we have web, mobile and desktop apps with slight changes on the same code base (and some limitations too), I am writing the code on Angular 2. It's for demonstration purposes only...

This is with the purpose of make available the API app and the API consumer on the same project and having the latest fixes/features available on both sides. Even when this maybe means have a like Hello-API consumer core.

Or is a better idea to make these pieces separated?

Thanks!!

**Comment by Mahmoudz** [comment]
@llstarscreamll I used to have this structure:

```
- Project 1
  - Server (Laravel API code)
  - Clients
    - Web
      - Angular
    - Mobile
      - Android
      - iOS
```

Let me know what you think of it

**Comment by llstarscreamll** [comment]
Looks nice, and make use of [git sparse checkout](http://stackoverflow.com/a/13738951) feature for develop/deploy the right folder on the right side.

Thank you so much!!
