### ISSUE TITLE
ApplicationAuthentication syntax error

### ISSUE THREAD

**Issue by markierung** [Porto-SAP/Hello-API#81]
Hi @Mahmoudz,

I got new bugs in "app/Containers/Application/Middlewares/MiddlewaresLoaderTrait.php", on doing a GET REQUEST.

`message: "syntax error, unexpected '->' (T_OBJECT_OPERATOR)",
code: 4,
status_code: 500,` 
on line 104 in:
`return (App::make(\Dingo\Api\Http\Middleware\Auth::class))->handle($request, $next); `

**Comment by Mahmoudz** [comment]
I think this is an error caused by your environment since the tests are passing on the CI. Which PHP version are you using!? I'm only testing my code on PHP 7+ and unlike Laravel 5.3 Hello API is not compatible with 5.6 anymore.

**Comment by markierung** [comment]
Yes!.. It was the PHP version!!.. Now i have Php v7.1.. but after i update my PHP i had to clear the api cache with:
 `php artisan api:cache` 
 and ..
`php artisan route:cache`

Now my Project is working as spected..

Thanks @Mahmoudz
