### ISSUE TITLE
Error on fresh installation

### ISSUE THREAD

**Issue by fabricelepro** [Porto-SAP/Hello-API#84]
Hi, i have installed Porto, and i have this issue on fresh installation
**The Response content must be a string or object implementing __toString()**

**Comment by Mahmoudz** [comment]
@fabricelepro thanks for letting me know, I'll try a fresh install right now.

**Comment by Mahmoudz** [comment]
@fabricelepro I just did that using `composer create-project porto-sap/hello-api hello-api` and it worked! can you please share with me the steps to help me reproduce your error

**Comment by fabricelepro** [comment]
Hi @Mahmoudz maybe it is because i haven't redis in my computer

**Comment by llstarscreamll** [comment]
@fabricelepro if you are using Ubuntu you can follow this [guide to install Redis on Ubuntu 16.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04) or use [Laravel Homestead](https://laravel.com/docs/5.4/homestead) or [LaraDock](https://github.com/laradock/laradock) as sugested on [Hello-API docs](https://hello-api.readme.io/docs/installation)... :smile:

**Comment by fabricelepro** [comment]
the command "php artisan jwt:generate" dont feel the entry on the .env file. the command is correctly run

**Comment by llstarscreamll** [comment]
Yes, it's a know jwt-auth issue, you should copy the generated key from command line on the .ENV file key manually...

**Comment by fabricelepro** [comment]
Yess. done.
