### ISSUE TITLE
About the containers generator and base layout

### ISSUE THREAD

**Issue by llstarscreamll** [Porto-SAP/Hello-API#87]
Hi, I have reading the Generator container for Hello-API, looks great!! I understand that it’s a on progress work yet, but I want to contribute with a package that I use on my projects to make quick CRUD apps (CrudGenerator) with a web GUI.
I have been writing some code to generate Porto containers and I want to share you the CRUDGenerator package, this package has some dependencies that I have to write to make compatible with Hello-API, the most important is the template layout system, which would be useful for all the containers that serve html, it would be the base html layout… so, would you let me contribute with this?
I have never shared my work with other developers, I'm a novel programmer but I will try my best for follow the Porto conventions and improve my self to make a good job…

I will be attentive to your comments…

PD: I have a basic Angular 2 app (not a private repo) that consumes the Hello-API, I want to share this project here too, but I don’t know if it is under the Porto-SAP scope.

**Comment by nmrgt** [comment]
Hi, 

There is a [repository](https://github.com/Porto-SAP/Generator) with a Porto generator - still in development. I'm quite busy right now so I haven’t finish but if you want to contribute I would be happy to work with you. 

For the CrudGenerator, I think it'll be useful for the admin container. What are the packages used to develop it ?

**Comment by Mahmoudz** [comment]
@llstarscreamll and @nmrgt thanks you for your interest in helping to make this project great.

@llstarscreamll that sounds great, and I do encourage you to start sharing your code :) I'd like to see that template layout system, contribute that to a separate branch to check it and test it.. Not sure about the Angular app, but if it's a simple demo that shows some of the features of Hello API by integrating with it. It might be cool idea, but this needs a separate repo, I'll create one and share it with you.

Regarding the Generator and its Web GUI, @nmrgt made a great contribution there, but it needs to be completed, so if you'd like to check it out and finish it, it would be awesome and I think @nmrgt will be able to help you get started...

Best,

**Comment by llstarscreamll** [comment]
Thank you guys!!

@nmrgt I'm busy now too, I would like to make things done to continue with my work, since I will build a new project based on Hello-API soon... so the CrudGenerator would be a nice feature for fast development. So, how I can help you? Where to start?

To clarify, Porto Generator and CrudGenerator are the same thing? or not? I intend to generate a Porto Container with CrudGenerator having the basic functionalities like tests, controllers, views, models, etc... As I can see, your generator will build this stuff too... We should stick with one package only or have both? I turned public [the repo](https://github.com/llstarscreamll/CrudGenerator), the readme file is in spanish, but the important section is the generated files/classes:

```
- Ads routes to `routes/web.php`
- Controller
- Model
- Model repo contract and implementation
- Seeders
- Models Factories
- Search Criteria
- Service class
- Spanish language file
- Views:
    - partials/
        - form-scripts
        - form-assets
        - heading
        - index-assets
        - index-buttons
        - form-fields
        - hidden-form-fields
        - index-create-form
        - index-table
        - index-table-header
        - index-table-search
        - index-table-body
    - index
    - create
    - show
    - edit
- Codeception functional Tests, each test with his own pageObject and tag group if needed:
    - Index, here are some tests for data restore if the entity has `deleted_at` attribute
    - Create
    - Edit
    - Show
    - Destroy
    - Permissions
```

Offcorss, the code generated is for a standard Laravel app with Codeception configured... it needs a lot of refactor and the generated code use abstract classes, language files and some helpers from a "CoreModule". You can check the generated code in `tests/_data` folder.

Here are some screenshots from the views generated:
![kazam_screenshot_00012](https://cloud.githubusercontent.com/assets/2442445/22895594/09f78a90-f1eb-11e6-80d6-e48d525e0ae7.png)

![kazam_screenshot_00015](https://cloud.githubusercontent.com/assets/2442445/22895778/acd5f706-f1eb-11e6-96e8-714e8d03a5d6.png)

![kazam_screenshot_00014](https://cloud.githubusercontent.com/assets/2442445/22895797/b6cf6fbc-f1eb-11e6-9440-c20e67d68fcb.png)

**Comment by llstarscreamll** [comment]
@Mahmoudz I will be start with the basic layout, I'm not a designer, so we should use some existing dashboard theme, maybe [AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/index2.html) or standard [Bootstrap](http://getbootstrap.com/)?

**Comment by Mahmoudz** [comment]
@llstarscreamll I just wanna make sure I understand you correctly, is that the workflow in your mind:

1. user opens the generator GUI App and see an interface similar to the one above.
2. user fill some details about his container, like: need model Car and model Bike, with basic CRUD endpoints, and properties (colour, speed, id)...
3. the GUI execute commands in the CLI or directly call functions on the generator core itself, to generate the container, based on the user input.
4. generator create a folder with model, repo, UI, basic request, CRUS tasks and Actions,......
5. the user can modify the container anyway he wants to add his custom business logic after being generated.

**Comment by llstarscreamll** [comment]
Yes, all right @Mahmoudz. The above is the generated views and this is the CRUD form setup:
![kazam_screenshot_00016](https://cloud.githubusercontent.com/assets/2442445/22899175/ef8cf9d0-f1f7-11e6-918c-04c7cec0342b.png)

**Comment by Mahmoudz** [comment]
@llstarscreamll looks so exciting.

Also, stay tuned I just started upgrading to L5.4 should be available today or tomorrow.

**Comment by nmrgt** [comment]
@llstarscreamll Thanks for sharing this ! Can you look on the container generator repository ? I can explain the approach I choose for the generator (by the way, we maybe can continue this discussion in this repo). 

I started to build a GUI with Vuejs but you can start a new one from scratch with angular. The main idea is that the generator serve some JSON shema and the Gui build a form generated from the JSON schema and send it to the controller (or you can download it and use CLI to generate).

At the moment, the generator works (we just need to write file instead of printing them on console output from CLI) and I think I made some modifications but didn't push them to the repo, let me check. If needed, we can skype or whatsapp (I'm in Paris (France), so maybe in the morning for you will be simpler for me).

**Comment by llstarscreamll** [comment]
@nmrgt great!! I will check the repo, see you there!!
