### ISSUE TITLE
Tests fails if config('app.locale') is different than 'en'

### ISSUE THREAD

**Issue by llstarscreamll** [Porto-SAP/Hello-API#89]
I have playing with the containers language files, and have that if I change the locale app config to spanish (or whatever different from english) many tests fails... Why? The error seems related to the spatie package tables... I have wasted three hours finding the error, but really? the local config? WTH!!... this is so weird, I have missed something?

I solve this bug adding a env variable to the `phpunit.xml` file setting locale to *en*.

**Comment by Mahmoudz** [comment]
Yep I think that needs to be documented.
