### ISSUE TITLE
Unable to list all registered web/api routes

### ISSUE THREAD

**Issue by jbaron-mx** [Porto-SAP/Hello-API#94]
## Versions
  - Hello-API: v2.2.0.
  - Dev environment: Laravel Homestead.

## Steps to reproduce
<img width="717" alt="screen shot 2017-02-22 at 11 37 01 pm" src="https://cloud.githubusercontent.com/assets/11150471/23246348/7b49027c-f958-11e6-86ae-59f5fe688658.png">

<img width="718" alt="screen shot 2017-02-22 at 11 37 23 pm" src="https://cloud.githubusercontent.com/assets/11150471/23246350/7f3dc5c0-f958-11e6-8dfd-07548b964282.png">

**Comment by jbaron-mx** [comment]
PR submitted :)

**Comment by Mahmoudz** [comment]
@jbaron-mx The reason I forget this container is because when I do changes I do them in existing projects built on top of Hello API, then I cherry-pick some commits to Hello API.. But the SocialAuth container is not part of that party :P Thank you
