### ISSUE TITLE
about view('login') a question.

### ISSUE THREAD

**Issue by hezhiying** [Porto-SAP/Hello-API#96]
First of all, my English is very sorry.
There are two customizations in the container directory
for example：
app\Containers\Admin:
    UI\Controllers\Controller.php
    UI\Views\login.blade.php
app\Containers\User
    UI\Controllers\Controller.php
    UI\Views\login.blade.php

Have the following code
`view('login');`

The problem is coming,The loaded view file will only be this：`app\Containers\Admin\UI\Views\login.blade.php`

what Preferentially load the view file under its own container?
Tanks.

**Comment by Mahmoudz** [comment]
@hezhiying Sorry for missing this Issue! I didn't saw it.

Version v2.4.0 have introduced namespacing for Views and Translations loaded from Containers. So now you use the views as follow: 

```php
view('user::login'); // from the User Container
view('admin::login'); // from the Admin Container
```
