### ISSUE TITLE
Error accessing API routes

### ISSUE THREAD

**Issue by llstarscreamll** [Porto-SAP/Hello-API#97]
Hi @Mahmoudz, I have test the last release (2.3.2) and found that API routes are now inaccessible, if I try API routes with Postman like `api.hello.dev` the response is the html view from Welcome container. For other API routes the response is html 404 (i.e. `api.hello.dev/auth`). I have missing something with these new release?

I have tried with a fresh install.

Cheers!!

**Comment by Mahmoudz** [comment]
@llstarscreamll sorry for that, if you use v2.4.* the problem should be gone.

That error was undetectable by the tests.

**Comment by llstarscreamll** [comment]
Thank you so much!! Everything is fine!!
