### ISSUE TITLE
routing issue with api 

### ISSUE THREAD

**Issue by rockers007** [Porto-SAP/Hello-API#99]
1. when I load http://api.homestead.app url in browser  it return this message
Hello API
(Porto SAP)

instead of "welcome hello api" from api response

2.when I tried to call http://api.homestead.app/register with parameter then I got
NotFoundHtt pException in RouteCollection.php line 161:

**Comment by rockers007** [comment]
solved by match .env file variable 

APP_URL=homestead.app
APP_FULL_URL=homestead.app
API_DOMAIN=api.homestead.app

**Comment by rockers007** [comment]
but now getting this error when call http://api.homestead.app/register

Socket error 0: php_network_getaddresses: getaddrinfo failed: No such host is known.  (connecting to beanstalkd:11300)

**Comment by rockers007** [comment]
solved by help with this link https://laravelista.com/posts/using-beanstalkd-with-laravel

**Comment by Mahmoudz** [comment]
@rockers007 glad it's working now :) Thanks for sharing the solutions.

**Comment by skobak** [comment]
I found the solution!
When you change your data in **.env**  file
`APP_NAME="lk"
APP_URL=http://lk.test
API_URL=http://api.lk.test
`
don't forget to run artisian command to clear  **config cache**:
`
php artisan config:cache
`
